upstream compreface_api {
  server compreface-api:8080;
}
upstream compreface_admin {
  server compreface-admin:8080;
}

server {
  listen 80;

  # API CompreFace (reconnaissance)
  location /api/v1/ {
    proxy_pass http://compreface_api;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  # Admin UI
  location / {
    proxy_pass http://compreface_admin;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
